#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
//! The JSON Schemas checked into `schemas/v1/` are generated, not hand-written.
//!
//! Drift between the Rust contracts and the published schemas would let a record pass one and fail
//! the other, so the checked-in files must match the generated bytes exactly.

use std::path::PathBuf;

use agent_jit_domain::schema::{SCHEMA_DIR, ValidationError, generated_schemas, validate_document};

fn schema_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(SCHEMA_DIR)
}

#[test]
fn every_record_kind_has_a_generated_schema() {
    let names: Vec<&str> = generated_schemas()
        .iter()
        .map(|schema| schema.schema_name)
        .collect();
    assert_eq!(
        names,
        vec![
            "agent_jit.benchmark_record",
            "agent_jit.candidate_contract",
            "agent_jit.capability_version",
            "agent_jit.event",
            "agent_jit.group",
            "agent_jit.invocation",
            "agent_jit.outcome",
            "agent_jit.replay_result",
            "agent_jit.repository",
            "agent_jit.session",
            "agent_jit.trajectory",
            "agent_jit.workflow",
        ]
    );
}

#[test]
fn checked_in_schemas_match_the_generated_bytes() {
    let root = schema_root();
    for schema in generated_schemas() {
        let path = root.join(&schema.file_name);
        let on_disk = std::fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!(
                "{} is missing ({error}); regenerate with `agent-jit schema generate`",
                path.display()
            )
        });
        assert_eq!(
            on_disk,
            schema.contents,
            "{} is stale; regenerate with `agent-jit schema generate`",
            path.display()
        );
    }
}

#[test]
fn the_schema_directory_contains_nothing_else() {
    let root = schema_root();
    let mut found: Vec<String> = std::fs::read_dir(&root)
        .unwrap()
        .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
        .collect();
    found.sort();

    let mut expected: Vec<String> = generated_schemas()
        .iter()
        .map(|schema| schema.file_name.clone())
        .collect();
    expected.sort();

    assert_eq!(found, expected);
}

#[test]
fn each_schema_pins_its_name_and_version_as_constants() {
    for schema in generated_schemas() {
        let parsed: serde_json::Value = serde_json::from_str(&schema.contents).unwrap();
        assert_eq!(
            parsed
                .pointer("/properties/schema/const")
                .and_then(serde_json::Value::as_str),
            Some(schema.schema_name),
            "{} does not pin its schema name",
            schema.file_name
        );
        assert_eq!(
            parsed
                .pointer("/properties/version/const")
                .and_then(serde_json::Value::as_u64),
            Some(u64::from(schema.version)),
            "{} does not pin its version",
            schema.file_name
        );
    }
}

fn valid_document() -> serde_json::Value {
    serde_json::json!({
        "schema": "agent_jit.trajectory",
        "version": 1,
        "id": "trj_01J0000000000000000000000A",
        "provenance": {
            "produced_by": "agent-jit/0.1.0",
            "source": "recorded",
            "recorded_at_unix_ms": 1_756_000_000_000_i64,
            "parents": []
        },
        "body": {
            "session_id": "ses_01J0000000000000000000000S",
            "repository_id": "rep_01J0000000000000000000000R",
            "head_commit": "0000000000000000000000000000000000000000",
            "intent": "validate this change the way this repository expects",
            "events": [],
            "outcome_id": null,
            "started_at_unix_ms": 1_756_000_000_000_i64,
            "duration_ms": 42_000
        }
    })
}

#[test]
fn a_well_formed_document_validates_and_reports_its_digest() {
    let validated = validate_document(&valid_document()).unwrap();
    assert_eq!(validated.schema_name, "agent_jit.trajectory");
    assert_eq!(validated.version, 1);
    assert_eq!(validated.id, "trj_01J0000000000000000000000A");
    assert_eq!(validated.digest.to_string().len(), 64);
}

#[test]
fn an_unknown_schema_name_is_refused() {
    let mut document = valid_document();
    document["schema"] = serde_json::json!("agent_jit.invented");
    let error = validate_document(&document).unwrap_err();
    assert_eq!(error.code(), "schema_unsupported");
}

#[test]
fn an_unknown_version_is_refused() {
    let mut document = valid_document();
    document["version"] = serde_json::json!(7);
    let error = validate_document(&document).unwrap_err();
    assert_eq!(error.code(), "schema_unsupported");
    assert!(matches!(error, ValidationError::Unsupported { .. }));
}

#[test]
fn an_unknown_body_field_is_refused_rather_than_ignored() {
    let mut document = valid_document();
    document["body"]["surprise"] = serde_json::json!(1);
    let error = validate_document(&document).unwrap_err();
    assert_eq!(error.code(), "schema_invalid_record");
}

#[test]
fn a_float_metric_is_refused() {
    let mut document = valid_document();
    document["body"]["duration_ms"] = serde_json::json!(42.5);
    let error = validate_document(&document).unwrap_err();
    assert_eq!(error.code(), "schema_invalid_record");
}
